version: '3.1'
services:
  stats-server:
    build: statistics/
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats_password

  stats-db:
    image: postgres:14-alpine
    container_name: stats-postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats_password
      - POSTGRES_DB=stats

  ewm-service:
    build: ewm-server/
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATISTICS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm_password

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm_password
      - POSTGRES_DB=ewm
